base/urls.py
from django.urls import path, include
from . import views
from .views import home

urlpatterns = [
    path('', home, name="base-home"),
]

cell/urls.py
from django.urls import path, include
from . import views
# CellUserCreateView
urlpatterns = [
    path('', views.home, name="home"),
    path('groups/create/', views.CreateCellGroupView.as_view(), name="create-cell-group"),
    path('members/create/', views.CreateMemberView.as_view(), name="create-member"),
    path('members/<member_id>/user/', views.CellUserCreateView.as_view(), name="create-member-user"),
    path('members/upload/', views.MembersUploadView.as_view(), name="upload-members"),
    path('contributions/create/', views.CreateContributionView.as_view(), name="create-contribution"),
    path('payments/create/', views.CreatePaymentView.as_view(), name="create-payment"),
]

cell_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users.views import ChangeMyPasswordView

urlpatterns = [
    path('', include('cell.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('changemypassword/', ChangeMyPasswordView.as_view(), name='change-password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cell/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from auditlog.registry import auditlog
from auditlog.models import LogEntry


class CellGroup(models.Model):
    name = models.CharField(max_length=100)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    record_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('home')


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    cell_group = models.ForeignKey(CellGroup, on_delete=models.CASCADE)
    record_date = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='member_created_by')
    name = models.CharField(max_length=100)
    phone_no = models.CharField(max_length=20, null=True)

    class Meta:
        unique_together = ('name', 'cell_group',)
        ordering = ['name']

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('create-member')


class Contribution(models.Model):
    cell_group = models.ForeignKey(CellGroup, on_delete=models.CASCADE)
    record_date = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=0)
    created_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='contribution_created_by')

    class Meta:
        ordering = ['-record_date']

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('create-contribution')


class Payment(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    contribution = models.ForeignKey(Contribution, on_delete=models.CASCADE)
    record_date = models.DateTimeField(default=timezone.now)
    amount = models.DecimalField(max_digits=10, decimal_places=0)
    created_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='payment_created_by')
    cell_group = models.ForeignKey(CellGroup, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-record_date']

    def __str__(self):
        return f'{self.member} - {self.contribution} - {self.amount}'

    def get_absolute_url(self):
        return reverse('create-payment')


# Audit Logs
auditlog.register(CellGroup)
auditlog.register(Member)
auditlog.register(Contribution)
auditlog.register(Payment)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Permission(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}'


class Role(models.Model):
    name = models.CharField(max_length=100)
    is_internal = models.BooleanField(default=False)
    permissions = models.ManyToManyField(Permission)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return f'{self.name}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    role = models.ForeignKey(Role, on_delete=models.PROTECT, null=True)
    # 0 - ticket issuer, 1 - company admin, 2 - internal users, 3 - root user
    # access_level = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user.username}'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

cell/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import CellGroup, Member, Contribution, Payment
from users.models import Role


class MembersUploadForm(forms.Form):
    members_file = forms.FileField()


class AddCellUserForm(forms.Form):
    def __init__(self, company_id=None, *args, **kwargs):
        super(AddCellUserForm, self).__init__(*args, **kwargs)
        self.fields['username'] = forms.CharField()
        self.fields['email'] = forms.EmailField()

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.core.validators import RegexValidator


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class PasswordChangeForm(forms.Form):
    new_password = forms.CharField(
        label="Enter your new password",
        widget=forms.PasswordInput,
        validators=[RegexValidator(r'^[a-zA-Z]{1}[a-zA-Z0-9]{5,9}$', message="Valid password start with letter, length between 6 and 10 characters")]
    )

cell/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import CellGroup, Member, Contribution, Payment
from django.views.generic.edit import FormView
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django import forms
# from .forms import CellGroupForm
from django.urls import reverse
from django.db.models import Avg, Count, Min, Sum
from django.http import HttpResponse
from .resources import MemberResource
from tablib import Dataset
from .forms import MembersUploadForm, AddCellUserForm


def home(request):
    member = None
    try:
        member = request.user.member if request.user.is_authenticated else None
    except Exception as e:
        print(e)
    contr_summary = []
    if member:
        contr_summary = Contribution.objects.filter(cell_group=member.cell_group).annotate(
            p_count=Count('payment'), p_total=Sum('payment__amount'))
    context = {
        'contr_summary': contr_summary
    }
    return render(request, 'cell/home.html', context)


class CreateCellGroupView(LoginRequiredMixin, CreateView):
    model = CellGroup
    fields = ['name']
    template_name = 'cell/cell_group_form.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class CreateMemberView(LoginRequiredMixin, CreateView):
    model = Member
    fields = ['name', 'phone_no']
    template_name = 'cell/cell_member_form.html'

    def form_valid(self, form):
        user = self.request.user
        form.instance.created_by = user
        form.instance.cell_group = user.member.cell_group
        return super().form_valid(form)


class CreateContributionView(LoginRequiredMixin, CreateView):
    model = Contribution
    fields = ['name', 'amount']
    template_name = 'cell/cell_contribution_form.html'

    def form_valid(self, form):
        user = self.request.user
        form.instance.created_by = user
        form.instance.cell_group = user.member.cell_group
        return super().form_valid(form)


class CreatePaymentView(LoginRequiredMixin, CreateView):
    model = Payment
    fields = ['member', 'contribution', 'amount']
    template_name = 'cell/cell_payment_form.html'

    def form_valid(self, form):
        user = self.request.user
        form.instance.created_by = user
        form.instance.cell_group = user.member.cell_group
        return super().form_valid(form)


class MembersUploadView(FormView):
    template_name = 'cell/members_upload.html'
    form_class = MembersUploadForm
    success_url = '/'
    fields = ['members_file']

    def form_valid(self, form):
        mr = MemberResource()
        dataset = Dataset()
        new_members = self.request.FILES['members_file']
        cell_group_id = self.request.user.member.cell_group.id
        user_id = self.request.user.id

        data = dataset.load(new_members.read())

        data.append_col((cell_group_id,) * data.height, header='cell_group')
        data.append_col((user_id,) * data.height, header='created_by')
        result = mr.import_data(dataset, dry_run=True)  # Test the data import

        if not result.has_errors():
            mr.import_data(dataset, dry_run=False)  # Actually import now
        else:
            print('Errors: ', result.row_errors()[0][1][0].error)
        return super().form_valid(form)


class CellUserCreateView(LoginRequiredMixin, FormView):
    form_class = AddCellUserForm
    template_name = 'cell/user_form.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        member_id = self.kwargs.get('member_id')
        kwargs['member'] = Member.objects.get(pk=member_id)
        return super(CellUserCreateView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        member_id = self.kwargs.get('member_id')
        data = form.cleaned_data
        user = User(username=data['username'], email=data['email'])
        user.set_password('Cell19')
        user.save()
        member = Member.objects.get(pk=member_id)
        member.user = user
        member.save()
        return super().form_valid(form)


def export_members(request):
    mr = MemberResource()
    dataset = mr.export()
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="members.csv"'
    return response


def members_upload(request):
    if request.method == 'POST':
        mr = MemberResource()
        dataset = Dataset()
        new_members = request.FILES['members_file']

        imported_data = dataset.load(new_members.read())
        result = mr.import_data(dataset, dry_run=True)  # Test the data import

        if not result.has_errors():
            mr.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'cell/members_upload.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.views.generic.edit import FormView
from .forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been created, you can now login')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)


class ChangeMyPasswordView(LoginRequiredMixin, FormView):
    form_class = PasswordChangeForm
    template_name = 'users/changemypassword_form.html'
    success_url = '/'

    def form_valid(self, form):
        data = form.cleaned_data
        print('Cleaned data: ', form.cleaned_data)
        user = User.objects.filter(pk=self.request.user.id).first()
        user.set_password(data['new_password'])
        user.save()
        return super().form_valid(form)

cell/templates/cell/cell_contribution_form.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="borde-botton mb-2">New Contribution</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <a class="btn btn-outline-info" href="{% url 'home' %}">Cancel</a>
                <button class="btn btn-primary" type="submmit">Create New Contribution</button>
            </div>
        </form>
    </div>
    {% if user.is_authenticated %}
        {% if user.member %}
            {% if user.member.cell_group.contribution_set.all %}
                <h5>List of contributions</h5>
                <table class="table table-sm table-hover">
                    <tr>
                        <th>Name</th>
                        <th>Date Created</th>
                        <th>Amount</th>
                    </tr>
                    {% for m in user.member.cell_group.contribution_set.all %}
                        <tr>
                            <td>{{ m.name }}</td>
                            <td>{{ m.record_date|date:"d/m/Y" }}</td>
                            <td>{{ m.amount|intcomma }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>No records to display</p>
            {% endif %}
        {% else %}
            <p>This application is for management of cell groups. However, you are not linked to any cell group right now!</p>
            <a class="btn btn-primary btn-sm" href="{% url 'create-cell-group' %}">Create new cell group</a>
        {% endif %}
    {% else %}
        <p>You are not logged in yet!</p>
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
{% endblock content%}

cell/templates/cell/cell_group_form.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="borde-botton mb-4">New Cell Group</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submmit">Create Cell Group</button>
            </div>
        </form>
    </div>
{% endblock content%}

cell/templates/cell/cell_member_form.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="borde-botton mb-2">New Member or <a href="{% url 'upload-members' %}">Upload Batch</a></legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <a class="btn btn-outline-info" href="{% url 'home' %}">Cancel</a>
                <button class="btn btn-primary" type="submmit">Create New Member</button>
            </div>
        </form>
    </div>
    {% if user.is_authenticated %}
        {% if user.member %}
            {% if user.member.cell_group.member_set.all %}
                <h5>List of members</h5>
                <table class="table table-sm table-hover">
                    <tr>
                        <th>Name</th>
                        <th>Phone No</th>
                        <th>User</th>
                        <!-- <th>Date Created</th>
                        <th>Created By</th> -->
                    </tr>
                    {% for m in user.member.cell_group.member_set.all %}
                        <tr>
                            <td>{{ m.name }}</td>
                            <td>{{ m.phone_no }}</td>
                            <td>
                            {% if m.user %}
                                {{ m.user }}
                            {% else %}
                                <a role="button" class="btn btn-sm btn-outline-secondary" href="{% url 'create-member-user' m.id %}">Add User</a>
                            {% endif %}
                            </td>
                            <!-- <td>{{ m.record_date|date:"d/m/y H:i" }}</td>
                            <td>{{ m.created_by }}</td> -->
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>No records to display</p>
            {% endif %}
        {% else %}
            <p>This application is for management of cell groups. However, you are not linked to any cell group right now!</p>
            <a class="btn btn-primary btn-sm" href="{% url 'create-cell-group' %}">Create new cell group</a>
        {% endif %}
    {% else %}
        <p>You are not logged in yet!</p>
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
{% endblock content%}

cell/templates/cell/cell_payment_form.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="borde-botton mb-2">Add Payment</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <a class="btn btn-outline-info btn-sm" href="{% url 'home' %}">Cancel</a>
                <button class="btn btn-primary btn-sm" type="submmit">Collect Payment</button>
            </div>
        </form>
    </div>
    {% if user.is_authenticated %}
        {% if user.member %}
            {% if user.member.cell_group.payment_set.all %}
                <h5>List of payments</h5>
                <table class="table table-sm table-hover">
                    <tr>
                        <th>Contribution</th>
                        <th>Member</th>
                        <th>Amount</th>
                        <th>Date</th>
                        <!-- <th>Created By</th> -->
                    </tr>
                    {% for m in user.member.cell_group.payment_set.all %}
                        <tr>
                            <td>{{ m.contribution }}</td>
                            <td>{{ m.member }}</td>
                            <td>{{ m.amount|intcomma }}</td>
                            <td>{{ m.record_date|date:"d/m/Y" }}</td>
                            <!-- <td>{{ m.created_by }}</td> -->
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>No records to display</p>
            {% endif %}
        {% else %}
            <p>This application is for management of cell groups. However, you are not linked to any cell group right now!</p>
            <a class="btn btn-primary btn-sm" href="{% url 'create-cell-group' %}">Create new cell group</a>
        {% endif %}
    {% else %}
        <p>You are not logged in yet!</p>
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
{% endblock content%}

cell/templates/cell/home.html
{% extends "base/base.html" %}
{% load humanize %}
{% block content %}
    {% if user.is_authenticated %}
        {% if user.member %}
            <div class="card mb-2">
              <div class="card-header">{{ user.member.cell_group }}</div>
              <div class="card-body row">
                 <div class="menu-btn col-md-4">
                     <a class="btn" href="{% url 'create-payment' %}">Payments <span class="badge badge-info">{{ user.member.cell_group.payment_set.count }}</span></a>
                 </div>
                 <div class="menu-btn col-md-4">
                     <a class="btn" href="{% url 'create-contribution' %}">Contributions <span class="badge badge-info">{{ user.member.cell_group.contribution_set.count }}</span></a>
                 </div>
                 <div class="menu-btn col-md-4">
                     <a class="btn" href="{% url 'create-member' %}">Members <span class="badge badge-info">{{ user.member.cell_group.member_set.count }}</span></a>
                 </div>
              </div>
              {% if contr_summary %}
                <div id="home-summary" class="card-footer text-muted">
                    Summary
                    <table class="table table-sm">
                        <tr>
                            <th>Name</th>
                            <th>Count</th>
                            <th>Amount</th>
                        </tr>
                        {% for m in contr_summary %}
                            <tr>
                                <td>{{ m.name }}</td>
                                <td>{{ m.p_count }}</td>
                                <td>{{ m.p_total|intcomma }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
              {% endif %}
            </div>
        {% else %}
            <p>This application is for management of cell groups. However, you are not linked to any cell group right now!</p>
            <a class="btn btn-primary btn-sm" href="{% url 'create-cell-group' %}">Create new cell group</a>
        {% endif %}
    {% else %}
        <p>You are not logged in yet!</p>
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
{% endblock content%}

cell/templates/cell/members_upload.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="borde-botton mb-4">Members Batch Upload</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submmit">Create Members</button>
            </div>
        </form>
    </div>
{% endblock content%}

cell/templates/cell/user_form.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'create-member' %}">{{ member }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">New User</li>
          </ol>
        </nav>
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submmit">Save</button>
            </div>
        </form>
    </div>
{% endblock content%}